openapi: "3.0.0"
info:
  version: 1.0.0
  title: oas-template
paths: 
  /getUser/{id} : 
    $ref: "./users/get-user.yaml"


components:
  parameters:
    authorization:"./commons/parameters/author"
  schemas:
    $ref: "users/get-userResponse.yaml"
