openapi: "3.0.0"
info:
  version: 1.0.0
  title: oas-template
paths: 
  /getUser/{id} : 
    $ref: "./users/get-user.yaml"


components:
  parameters:
    id:
      -$ref: 
    authorization:
      $ref: "./commons/parameters/authorization.yaml"
  
  
