openapi: "3.0.0"
info:
  version: 1.0.0
  title: oas-template
  
"host": "csr91-check-in-papi.us-e2.cloudhub.io"

paths: 
  /getStudent/{id} : 
    $ref: "./users/get-student.yaml"


components:
  parameters:
    authorization:
      $ref: "./commons/parameters/authorization.yaml"
  
  schemas:
    errors:
      $ref: "./commons/error/error.yaml"
    get-studentResponse:
      $ref: "./users/get-studentResponse.yaml"
    

  responses:
    400:
      $ref: "./commons/error/400.yaml" 
  
  
